export { VinextAuth } from './handlers/index.js';
export { VinextAuth as default } from './handlers/index.js';

export type {
  VinextAuthConfig,
  VinextAuthHandlers,
  PagesRequest,
  PagesResponse,
  Session,
  DefaultSession,
  User,
  DefaultUser,
  JWT,
  DefaultJWT,
  OAuthProvider,
  CredentialsProvider,
  EmailProvider,
  EmailTransport,
  VerificationToken,
  Provider,
  CallbacksConfig,
  JWTCallbackParams,
  SessionCallbackParams,
  SignInCallbackParams,
  RefreshTokenCallbackParams,
  RefreshTokenCallbackResult,
  PagesConfig,
  SessionConfig,
  JWTConfig,
  AdapterInterface,
  AdapterSession,
  WithAuthOptions,
  SessionContextValue,
  SessionStatus,
  SignInOptions,
  SignOutOptions,
  AccountLinkingConfig,
  CredentialsConfig,
  RateLimiter,
  EventsConfig,
  VinextAuthErrorCode,
} from './types.js';

export { VinextAuthError } from './types.js';
export { InMemoryRateLimiter } from './core/rate-limiter.js';
