import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'react/index': 'src/react/index.ts',
    'server/index': 'src/server/index.ts',
    'middleware/index': 'src/middleware/index.ts',
    'providers/google': 'src/providers/google.ts',
    'providers/github': 'src/providers/github.ts',
    'providers/credentials': 'src/providers/credentials.ts',
    'providers/discord': 'src/providers/discord.ts',
    'providers/facebook': 'src/providers/facebook.ts',
    'providers/linkedin': 'src/providers/linkedin.ts',
    'providers/twitch': 'src/providers/twitch.ts',
    'providers/spotify': 'src/providers/spotify.ts',
    'providers/microsoft': 'src/providers/microsoft.ts',
    'providers/twitter': 'src/providers/twitter.ts',
    'providers/apple': 'src/providers/apple.ts',
    'providers/email': 'src/providers/email.ts',
    'adapters/cloudflare-kv': 'src/adapters/cloudflare-kv.ts',
    'adapters/cloudflare-kv-rate-limiter': 'src/adapters/cloudflare-kv-rate-limiter.ts',
    'adapters/cloudflare-d1': 'src/adapters/cloudflare-d1.ts',
  },
  format: ['esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: ['react', 'react-dom'],
  treeshake: true,
  target: 'es2022',
});
